name: Test Windows Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2025

    steps:
      - name: Check Windows
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Check Python
        run: |
          python --version

      - name: Check PowerShell
        run: |
          $PSVersionTable.PSVersion

      - name: Install Miniconda
        shell: powershell
        run: |
          Invoke-WebRequest `
            -Uri "https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe" `
            -OutFile "$env:RUNNER_TEMP\miniconda.exe"

          Start-Process `
            -FilePath "$env:RUNNER_TEMP\miniconda.exe" `
            -ArgumentList "/InstallationType=JustMe", "/RegisterPython=0", "/S", "/D=$env:RUNNER_TEMP\Miniconda3" `
            -Wait

      - name: Check Conda
        shell: powershell
        run: |
          & "$env:RUNNER_TEMP\Miniconda3\Scripts\conda.exe" --version
          
      - name: Create Python 3.8.5 environment
        shell: powershell
        run: |
          & "$env:RUNNER_TEMP\Miniconda3\Scripts\conda.exe" create -y -n temp_py38 python=3.8.5 pip

      - name: Check Python 3.8.5
        shell: powershell
        run: |
          & "$env:RUNNER_TEMP\Miniconda3\Scripts\conda.exe" run -n temp_py38 python --version
